export { default as HeroSection } from './HeroSection'
export { default as BrandsMarquee } from './BrandsMarquee'
export { default as CategoriesSection } from './CategoriesSection'
export { default as ServicesSection } from './ServicesSection'
export { default as FeaturedProducts } from './FeaturedProducts'
export { default as AboutSection } from './AboutSection'
export { default as LatestPosts } from './LatestPosts'
export { default as CtaSection } from './CtaSection'
